nextcloud/.github

.github/workflows/dispatch-workflow.yml, README.md
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>
=> Ass pr action

workflow-templates/command-rebase.yml
Signed-off-by: szaimen <szaimen@e.mail.de>
=> fix comment in rebase-command

.github/workflows/dispatch-workflow.yml
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>
=> Fix author in dispatch commit

.github/workflows/dispatch-workflow.yml
- Better intro comment
- Use different branch names for each workflow
- Spacing
=> Improve dispatch workflow

workflow-templates/dependabot-approve-merge.yml
=> Improve dependabot auto-approve-merge

workflow-templates/command-compile.yml
Live testing: https://github.com/nextcloud/photos/pull/734
=> Fix compile command

workflow-templates/appstore-build-publish.yml
Signed-off-by: John Molakvoæ <skjnldsv@protonmail.com>
=> Use nextcloud-releases/nextcloud-appstore-push-action

workflow-templates/dependabot-approve-merge.properties.json, workflow-templates/lint-eslint.properties.json, workflow-templates/lint-info-xml.properties.json, workflow-templates/lint-php-cs.properties.json, workflow-templates/lint-php.properties.json, workflow-templates/lint-stylelint.properties.json, workflow-templates/node.properties.json, workflow-templates/npm-publish.properties.json
Signed-off-by: John Molakvoæ <skjnldsv@protonmail.com>
=> Add filePatterns to workflows

workflow-templates/lint-php.yml
[Signed-off-by: John Molakvoæ <skjnldsv@protonmail.com>](https://github.com/nextcloud/server/issues/30896)
=> Drop php 7.3

workflow-templates/dependabot-approve-merge.yml, workflow-templates/lint-eslint.yml, workflow-templates/lint-info-xml.yml, workflow-templates/lint-php-cs.yml, workflow-templates/lint-php.yml, workflow-templates/lint-stylelint.yml, workflow-templates/node.yml
=> Add main trigger for pushes

workflow-templates/appstore-build-publish.yml, workflow-templates/command-compile.yml, workflow-templates/command-rebase.yml, workflow-templates/lint-eslint.yml, workflow-templates/lint-info-xml.yml, workflow-templates/lint-php-cs.yml, workflow-templates/lint-php.yml, workflow-templates/lint-stylelint.yml, workflow-templates/node.yml, workflow-templates/npm-publish.yml
1. Bump actions/checkout from 2 to 3
2. Bump skjnldsv/read-package-engines-version-actions from 1.1 to 1.2
3. Bump actions/setup-node from 2 to 3
=> Dependencies updates

workflow-templates/appstore-build-publish.yml
https://github.com/nextcloud-releases/preferred_providers/runs/5871283779
=> Do not build with krankerl if no config exists

workflow-templates/command-rebase.yml
Fix https://github.com/nextcloud/.github/issues/55
Signed-off-by: szaimen <szaimen@e.mail.de>
=> fix permissions for the rebase workflow

workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml
Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>
=> Add missing headers in phpunit workflows

workflow-templates/command-rebase.yml
See https://github.com/nextcloud/.github/pull/56
=> Bump cirrus-actions/rebase to 1.6

workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml
=> Run PHPUnit workflows on main branch

workflow-templates/block-merge-eol.yml, workflow-templates/block-merge-freeze.yml, workflow-templates/command-rebase.yml, workflow-templates/dependabot-approve-merge.yml, workflow-templates/fixup.yml, workflow-templates/lint-eslint.yml, workflow-templates/lint-info-xml.yml, workflow-templates/lint-php-cs.yml, workflow-templates/lint-php.yml, workflow-templates/lint-stylelint.yml, workflow-templates/node.yml, workflow-templates/npm-publish.yml, workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml
Bringing the suggestions from @nathannaveen upstream into the templates.
Disclaimer: I did not actually try if they all still work.
=> Add github permissions

workflow-templates/block-merge-eol.yml, workflow-templates/block-merge-freeze.yml, workflow-templates/dependabot-approve-merge.yml, workflow-templates/fixup.yml, workflow-templates/lint-eslint.yml, workflow-templates/lint-info-xml.yml, workflow-templates/lint-php-cs.yml, workflow-templates/lint-php.yml, workflow-templates/lint-stylelint.yml, workflow-templates/node.yml, workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml, workflow-templates/psalm.yml
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
=> Add cancel-in-progress to workflows

workflow-templates/phpunit-oci.yml
Signed-off-by: Joas Schilling <213943+nickvergessen@users.noreply.github.com>
=> Use ubuntu-latest for oracle

workflow-templates/fixup.yml, workflow-templates/lint-eslint.yml, workflow-templates/lint-php-cs.yml, workflow-templates/lint-php.yml, workflow-templates/lint-stylelint.yml, workflow-templates/node.yml, workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml, workflow-templates/psalm.yml
Signed-off-by: Joas Schilling <coding@schilljs.com>
=> Remove trailing space

workflow-templates/psalm-matrix.yml, workflow-templates/update-nextcloud-ocp-matrix.yml, workflow-templates/update-nextcloud-ocp.yml
Signed-off-by: Joas Schilling <213943+nickvergessen@users.noreply.github.com>
=> Remove stable23 as it is EOL

workflow-templates/appstore-build-publish.yml, workflow-templates/lint-php-cs.yml, workflow-templates/lint-php.yml, workflow-templates/phpunit-mysql.yml, workflow-templates/psalm.yml, workflow-templates/update-nextcloud-ocp.yml
Signed-off-by: Joas Schilling <coding@schilljs.com>
=> Fade out PHP 7.4

workflow-templates/phpunit-summary-when-unrelated.properties.json, workflow-templates/phpunit-summary-when-unrelated.yml
Signed-off-by: Joas Schilling <coding@schilljs.com>
=> Mark PHPUnit tests as passed when no PHP related files where changed

workflow-templates/update-nextcloud-ocp-matrix.yml
Follow-up to https://github.com/nextcloud/.github/pull/105
=> chore(ocp matrix bump): Use conventional commits

workflow-templates/node-when-unrelated.properties.json, workflow-templates/node-when-unrelated.yml
=> feat(node): add workflow to pass node when no JavaScript was changed

workflow-templates/update-nextcloud-ocp.yml
Signed-off-by: Jonas <jonas@freesources.org>
=> Add `main` branch to default branches in update-nextclod-ocp.yml

workflow-templates/command-compile.yml
- https://github.com/skjnldsv/check-actor-permission/tags
- https://github.com/skjnldsv/parse-command-comment/tags
=> chore(templates): update command-compile `check-actor-permission` and `parse-command-comment` versions

workflow-templates/appstore-build-publish.yml
Else the signing command fails
Signed-off-by: Robin Appelman <robin@icewind.nl>
=> Include submodule in appstore release server checkout

workflow-templates/command-compile.yml
Signed-off-by: Joas Schilling <213943+nickvergessen@users.noreply.github.com>
=> Switch to conventional commits

workflow-templates/block-merge-eol.yml
As requested in https://github.com/nextcloud/server/pull/37214#pullrequestreview-1341610031
=> update block-merge-eol to take in beta versions after branch-off

workflow-templates/block-merge-eol.yml, workflow-templates/block-merge-freeze.yml, workflow-templates/fixup.yml, workflow-templates/lint-eslint-when-unrelated.yml, workflow-templates/lint-eslint.yml, workflow-templates/lint-info-xml.yml, workflow-templates/lint-php-cs.yml, workflow-templates/lint-php.yml, workflow-templates/lint-stylelint.yml, workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml, workflow-templates/phpunit-summary-when-unrelated.yml
See https://github.com/nextcloud/server/pull/37320
=> Make sure workflows have unique name in the UI

workflow-templates/block-merge-eol.yml
Address https://github.com/nextcloud/.github/pull/130#discussion_r1138302899
=> update block-merge-eol workflow

workflow-templates/command-compile.yml
https://github.com/peter-evans/create-or-update-comment/pull/29
=> chore(commande-compile): fix deprecated `reaction-type` and upgrade dependencies

workflow-templates/npm-audit-fix.yml
Make sure that compiling happens always
=> update npm-audit-fix 2

workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml
https://www.youtube.com/watch?v=Bparw9Jo3dk&t=46s
=> fix(phpunit): Missing space hurts my eyes

workflow-templates/lint-info-xml.yml
Ref https://github.com/ChristophWurst/xmllint-action/pull/8
=> chore(deps): Update xmllint action to use an up to date base image

.github/workflows/fixup.yml, workflow-templates/fixup.yml
=> feat: migrate to skjnldsv/block-fixup-merge-action

workflow-templates/pr-feedback.properties.json
https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization
=> fix: icon name for pr feedback workflow

workflow-templates/npm-publish.yml
* Fix https://github.com/nextcloud/.github/pull/188#issuecomment-1617697850
=> fix(npm-publish): Set `packages: write` permission to publish on Github

workflow-templates/update-nextcloud-ocp-matrix.yml, workflow-templates/update-nextcloud-ocp.yml
* More analysis in https://github.com/nextcloud/spreed/pull/9995
* Sample issue in https://github.com/nextcloud/spreed/issues/10050
=> fix: Warn maintainers when nextcloud/ocp updates failed

workflow-templates/pr-feedback.yml
Afaik the "header" is not necessary, but nice to have and helps to understand that the workflow is updated automatically.
=> chore: add organization template hint to pr-feedback

workflow-templates/update-nextcloud-ocp-approve-merge.properties.json, workflow-templates/update-nextcloud-ocp-approve-merge.yml
Demo https://github.com/nextcloud/spreed/pull/11007
=> Add auto approve and merge workflow for nextcloud/ocp

README.md
=> chore(readme): add simple script to update workflows

workflow-templates/pr-feedback.yml
Can't say if we want to go for AGPL or a permissive license like MIT.
Shouldn't matter to much since `.github` folder should not be shipped anyways.
=> Add SPDX header

workflow-templates/pr-feedback.yml
Now processes the last 30000 issues instead of the first 3000
=> fix: pr-feedback workflow

workflow-templates/reuse.properties.json
=> Add description and icon to REUSE check action

workflow-templates/npm-audit-fix.yml
=> feat(npm-audit-fix): Add audit report to created pull request

non-community-usernames.txt, workflow-templates/pr-feedback.yml
I've created a new blacklist for this and other automations. This PR makes the pr-feedback bot use that blacklist
=> feat: Use new blocklist in pr-feedback.yml

.github/workflows/lint-yaml.yml, workflow-templates/dependabot-approve-merge.yml, workflow-templates/phpunit-oci.yml, workflow-templates/pr-feedback.yml
Tested in Talk for multiple months and it's working fine since we switched the oracle docker below.
Ref https://github.com/nextcloud/spreed/pull/12459/files#diff-45d24c7076121c126c6a08258caeb2b7b85b4039022a0162522ebb0b66a60145L59
=> fix(phpunit): Run OCI phpunit on ubuntu-latest

non-community-usernames.txt
I got dropped somewhere after #377, but before #368 got merged.
=> chore(non-community-usernames): Add myself, again

.github/workflows/reuse.yml, workflow-templates/reuse.yml
needed for https://github.com/nextcloud-libraries/nextcloud-event-bus/pull/801 to make that one turn green, see https://github.com/nextcloud-libraries/nextcloud-event-bus/actions/runs/9939820356
=> Reformat to not make `npx prettier` check fail

workflow-templates/command-compile.yml
Ref https://github.com/nextcloud/server/pull/46559
=> fix(compile): Fix compile command fork detection

non-community-usernames.txt
Username changed from fenn-cs to nfebe
=> chore: Update non-community-usernames.txt

non-community-usernames.txt
- add ZetaTom to avoid triggering feedback request action
- sort username list
=> chore(usernames): add ZetaTom

workflow-templates/command-compile.yml
https://github.com/nextcloud/.github/pull/431#discussion_r1760030627
=> fix(command-compile): cache restore action

workflow-templates/block-merge-eol.yml, workflow-templates/block-merge-freeze.yml
- Freeze Demo at https://github.com/nextcloud/notifications/pull/2152
- Ignoring unmatched base_ref at https://github.com/nextcloud/notifications/pull/2153
=> fix: Harden base_ref checks in block-merge actions

.github/workflows/dispatch-workflow.yml, .github/workflows/lint-yaml.yml, .github/workflows/reuse.yml, workflow-templates/appstore-build-publish.yml, workflow-templates/command-compile.yml, workflow-templates/command-openapi.yml, workflow-templates/cypress.yml, workflow-templates/documentation.yml, workflow-templates/npm-audit-fix.yml, workflow-templates/pr-feedback.yml, workflow-templates/psalm-matrix.yml, workflow-templates/psalm.yml, workflow-templates/reuse.yml, workflow-templates/update-nextcloud-ocp-matrix.yml, workflow-templates/update-nextcloud-ocp.yml
* Resolves https://github.com/nextcloud-libraries/nextcloud-vite-config/security/code-scanning/5
=> fix(reuse): Restrict workflow to read permissions

workflow-templates/update-nextcloud-ocp-matrix.yml
- Before: https://github.com/nextcloud/call_summary_bot/issues/115
- After: `Failed to update nextcloud/ocp package`
=> fix(ocp): Align matrix ocp update to fix typo in headline

non-community-usernames.txt
I don't want to receive the feedback-comments anymore on my PRs.
=> Add jaylinski to non-community username list

workflow-templates/appstore-build-publish.yml
- https://github.com/nextcloud/spreed/pull/8765
- https://github.com/nextcloud/mail/pull/8020
=> fix: Generate classmap-authoritative on release to improve performance

workflow-templates/appstore-build-publish.yml
=> Revert "fix: Generate classmap-authoritative on release to improve performance"

workflow-templates/npm-publish.yml
Saw it already a couple of times that package version and tag does not match...
=> feat(npm-publish): check that tag matches package.json version

workflow-templates/npm-audit-fix.yml
See https://github.com/nextcloud/viewer/actions/runs/15794013927
=> fix(npm-audit-fix): use default_branch

workflow-templates/node.yml
Since we could be using another bundler like vite
=> chore: Update build description

workflow-templates/renovate-approve-merge.properties.json
=> enh(templates): add description and icon for renovate-approve-merge

workflow-templates/psalm-matrix.yml, workflow-templates/psalm.yml
- Testing in Talk since ~9 months: https://github.com/nextcloud/spreed/pull/13933
=> feat(security): Check for vulnerable PHP dependencies
