nextcloud/.github

.github/workflows/lint-yaml.yml, workflow-templates/command-rebase.yml, workflow-templates/dependabot-approve-merge.yml, workflow-templates/node.yml
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>
=> Lint action templates

workflow-templates/appstore-build-publish.yml
Since we enforce running on https://github.com/nextcloud-releases, no need for admin, Just set your team rights to `write`
=> Remove admin permissions requirements

CONTRIBUTING.md, SECURITY.md
Fixes https://github.com/nextcloud/.github/issues/31
This is a copy of the CONTRIBUTING.md from server with two changes
* Dropped the dead IRC channel
* Dropped links to the server-specific issue template. Each repo has its own
* Dropped ref to server repo
* Minor adjustments
SECURITY.md was copied as is.
=> Add a global CONTRIBUTING.md and SECURITY.md for all orga repos

workflow-templates/block-merge-freeze.yml
Signed-off-by: John Molakvoæ <skjnldsv@protonmail.com>
=> Fix block-merge-freeze version.php download

workflow-templates/phpunit-mysql.properties.json, workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.properties.json, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.properties.json, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.properties.json, workflow-templates/phpunit-sqlite.yml, workflow-templates/phpunit.svg
Imported from app-tutorial.
Modified to detect APP_NAME from repository name.
Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>
=> Add workflows for phpunit

.github/dependabot.yml
This PR aims at also keeping the workflow templates updated with dependabot.
I have to admit, I am not entirely sure it works this way, but I guess we only find out, if we try :slightly_smiling_face: :see_no_evil:
=> Also update the workflow-templates with dependabot

workflow-templates/node.yml
Adds an explicit message about recompiling to avoid scratching heads.
Also highlight "Show changes on failure" in red so that it catches the
eye because it's easy to miss while scratching head.
Before:
After:
Note: I have changed the message since the screenshot, but you get the point.
Background:
This is a follow up on my frustration in https://github.com/nextcloud/recommendations/pull/514#issuecomment-1203860403 as I wasn't aware that asset compilation was required also for this repo because we don't have it elsewhere.
=> Improve UX when node job fails because of assets

workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml
This avoids having to list server master version number as compatible
too soon in the application info.xml
Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>
=> Force enable app in CI so that testing master with server master works

.github/workflows/lint-yaml.yml, workflow-templates/lint-eslint.yml, workflow-templates/lint-php-cs.yml, workflow-templates/lint-stylelint.yml
Aint nobody gonna check lint results of a direct push. This is a waste of CI time.
=> Lint only PRs, not pushes (or merges)

workflow-templates/phpunit-pgsql.yml
We should always fixate the image versions (oracle and mysql have it already). So that CI on stable branches is staying functional with whatever was supported at the time.
* https://github.com/nextcloud/server/issues/34617
All stable23 and stable24 branches in all apps will also need this patch as we will mostlikely not backport the fixes to support a new DB on a stable branch much further then the current one.
=> Fixate postgres image version

workflow-templates/appstore-build-publish.yml, workflow-templates/block-merge-eol.yml, workflow-templates/block-merge-freeze.yml, workflow-templates/command-compile.yml, workflow-templates/dependabot-approve-merge.yml, workflow-templates/lint-info-xml.yml
Should prevent PRs like https://github.com/nextcloud/registration/pull/476 in the future when people already copied the template (as copying removes trailing whitespace in an IDE)
Command used:
```
find . -name "*.yml" -type f -print0 | xargs -0 sed -i 's/[[:space:]]*$//'
```
=> Remove trailing whitespaces from templates

workflow-templates/lint-eslint.yml, workflow-templates/node.yml
In some apps like Talk this can free 2 more minutes of CI on every PHP based PR.
Additionally opted in for any js file (configs in root), package* (npm changes), workflow file changes as well as info.xml to run it on release PRs.
=> Only check JS compiling and eslint with relevant changes

.github/workflows/command-rebase.yml, .github/workflows/dispatch-workflow.yml, workflow-templates/appstore-build-publish.yml, workflow-templates/command-compile.yml, workflow-templates/command-rebase.yml, workflow-templates/npm-publish.yml
Ref https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#patching-your-actions-and-workflows
=> Set-output is deprecated

.github/workflows/command-rebase.yml, .github/workflows/dispatch-workflow.yml, .github/workflows/fixup.yml, .github/workflows/lint-yaml.yml, workflow-templates/appstore-build-publish.yml, workflow-templates/command-compile.yml, workflow-templates/command-rebase.yml, workflow-templates/dependabot-approve-merge.yml, workflow-templates/fixup.yml, workflow-templates/lint-eslint.yml, workflow-templates/lint-info-xml.yml, workflow-templates/lint-php-cs.yml, workflow-templates/lint-php.yml, workflow-templates/lint-stylelint.yml, workflow-templates/node.yml, workflow-templates/npm-publish.yml, workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml, workflow-templates/psalm-matrix.yml, workflow-templates/psalm.yml, workflow-templates/update-nextcloud-ocp-matrix.yml, workflow-templates/update-nextcloud-ocp.yml
I was going to open an issue for this, but I thought I could just open a PR to discuss it.
Pinning full commit SHAs is best practice for security. We recently did this in the Android repos and
I noticed that some of our workflows come from this repo.
Dependabot should also open PRs for this and update both the SHA and the comment, see [this issue](https://github.com/dependabot/dependabot-core/issues/4691)
Docs: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
Automatically pinned with https://github.com/mheap/pin-github-action and then cleaned up manually.
=> Pin Actions SHAs

workflow-templates/fixup.yml
It's discouraging to show failing CI at times where they are actually preferred over amend and rebase dances.
Tested at https://github.com/nextcloud/mail/pull/7793. The check was skipped for the draft PR but picked up when I clicked *Ready for review*
=> fix(fixup): Do not run fixup commit check for draft PRs

workflow-templates/appstore-build-publish.yml
Ref https://github.com/ChristophWurst/krankerl/releases/tag/v0.14.0
AFAIK, this is the only occurrence of krankerl.
=> chore: bump krankerl to 0.14.0

workflow-templates/lint-eslint-when-unrelated.yml, workflow-templates/lint-eslint.yml
Many apps make use of a dedicated `.eslintrc.js` config file
Ref https://eslint.org/docs/latest/user-guide/configuring/configuration-files#configuration-file-formats
Ref https://eslint.org/docs/latest/user-guide/configuring/ignoring-code#the-eslintignore-file
=> feat(eslint): run workflow on changed eslintrc and eslintingore

workflow-templates/appstore-build-publish.yml, workflow-templates/command-compile.yml, workflow-templates/lint-eslint.yml, workflow-templates/lint-stylelint.yml, workflow-templates/node.yml, workflow-templates/npm-publish.yml
Upgrade fallbacks to the currently minimum supported (as per https://github.com/nextcloud/standards/issues/5 ) versions.
=> Upgrade `fallbackNode` and `fallbackNpm` to Nextcloud supported versions

workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml
- Removes phpunit as a tool as we execute vendor/bin/phpunit anyway
- Improves cross copying the files when
+ phpunit.xml is in a non-default location or name (e.g. spreed, notifications, mail, …)
+ phpunit binary is in a non-default location e.g. vendor-bin/ (e.g. external, spreed, mail, ...)
Signed-off-by: Joas Schilling <coding@schilljs.com>
=> fix(phpunit): Move the phpunit configs to composer

workflow-templates/fixup.yml
By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened. https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
Signed-off-by: John Molakvoæ <skjnldsv@users.noreply.github.com>
=> fix(fixup): Add back `synchronize` event type

workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml
After copying the template to apps that use integration tests they started failing.
The issue is that the base features require admin:admin
https://github.com/nextcloud/server/blob/f5c361cf44739058b79f322576a1bad2d8c142d9/build/integration/features/bootstrap/BasicStructure.php#L213-L214
That was already used in Oracle, just MySQL, PostgreSQL and SQLite seem to have been copied from another repository and so used admin:password.
Ref https://github.com/nextcloud/notifications/pull/1424
=> fix(phpunit): Align admin credentials

workflow-templates/lint-php-cs.yml, workflow-templates/lint-php.yml, workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml, workflow-templates/psalm-matrix.yml, workflow-templates/psalm.yml
Ref https://github.com/nextcloud/server/pull/36375
=> feat(CI): Add PHPUnit testing for PHP 8.2

workflow-templates/update-nextcloud-ocp-matrix.yml, workflow-templates/update-nextcloud-ocp.yml
1. Drive-by fix: composer require of the OCP package is not continuing on error anymore.
2. Finally figured out why the OCP package always updates phpunit, psalm and more:
https://github.com/nextcloud/spreed/actions/runs/4586488511/jobs/8099376551#step:6:13
The problem is `git checkout` aborts all things when one path is not existing.
```
$ composer require --dev nextcloud/ocp:dev-stable26
…
git status && git clean -f 3rdparty vendor vendor-bin && git status && git checkout 3rdparty vendor vendor-bin && git status
On branch stable26
You are currently bisecting, started from branch 'stable26'.
(use "git bisect reset" to get back to the original branch)
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes …
```
=> fix(update-nextcloud-ocp): Fix resetting other dependencies

workflow-templates/npm-audit-fix.yml
Advantage: we only need to maintain the workflow in master and can trigger updates with one click.
Example run in https://github.com/nextcloud/viewer/actions/runs/4830795292
=> change npm-audit-fix into a matrix run

workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml, workflow-templates/update-nextcloud-ocp-matrix.yml, workflow-templates/update-nextcloud-ocp.yml
One step closer to fix the phpunit and be on the safe side for self-hosted runners.
Context:
- While we can reproduce a runner image that is very close to Github's officials, all php modules are not installed by default
- The images do provide a full php (8.1 iirc) setup, with various extensions, but not for other php versions
- e.g: https://github.com/nextcloud/integration_openproject/actions/runs/5077273637/jobs/9120346677 Failed on 7.4, as php 7.4 is not shipped with the image and GD extension was not requested by the `setup-php` workflow
=> fix: ensure proper php modules to setup Nextcloud

workflow-templates/psalm-matrix.yml
Example with patch: https://github.com/nextcloud/mail/actions/runs/5083890915/jobs/9135458154?pr=8496
Example without patch: https://github.com/nextcloud/social/actions/runs/5082148997/jobs/9131503707
=> allow dependency up downgrade for ocp peer dependencies

workflow-templates/documentation.yml
No need to check for author permission if we're just building the docs without publishing them
=> fix(documentation): allow to test build if we're not pushing new docs

workflow-templates/command-compile.yml
On server, this reduce the workflow time by half! :speedboat: :rocket: 
Do you see any other location this might be useful?
- No cache: https://github.com/skjnldsv/server/actions/runs/5364983983/jobs/9733513243
- Cache: https://github.com/skjnldsv/server/actions/runs/5365018048/jobs/9733568097
=> feat: cache git repository for faster checkout

workflow-templates/npm-publish.yml
Some packages like the `nextcloud-axios` package are already published on NPM **and** on GPR.
Pro: Less monopolization + redundancy
=> feat(npm-publish): Also publish packages on github package registry

workflow-templates/cypress.yml
- Disable npm cache because of https://github.com/actions/cache/issues/720 (we gain 30 seconds per runner)
- Fix node/npm engines output
- Fix fallbackNode and fallbackNpm versions
=> fix: cypress template

workflow-templates/update-nextcloud-ocp.yml
Noticed in https://github.com/nextcloud/notifications/issues/1629
```
notifications$ grep '/appinfo/info.xml' .github/CODEOWNERS | awk '{ print "codeowners="$2 }'
codeowners=@Antreesy
```
```
notifications$ grep '/appinfo/info.xml' .github/CODEOWNERS | cut -f 2- -d ' ' | xargs | awk '{ print "codeowners="$0 }'
codeowners=@Antreesy @nickvergessen
```
=> fix(update-nextcloud-ocp): Ping all maintainers

workflow-templates/appstore-build-publish.yml, workflow-templates/command-compile.yml, workflow-templates/documentation.yml, workflow-templates/lint-eslint.yml, workflow-templates/lint-stylelint.yml, workflow-templates/node-test.yml, workflow-templates/node.yml, workflow-templates/npm-audit-fix.yml, workflow-templates/npm-publish.yml
We run `npm ci` in a number of places
and usually we do not need cypress to be installed.
In text a [sample run](https://github.com/nextcloud/text/actions/runs/6025685889/job/16346936805?pr=4747#step:6:51) of `npm ci` without cypress took 24 sec. instead of [43 sec](https://github.com/nextcloud/text/actions/runs/6025539366/job/16346460340#step:6:49).
This also prevents run failures due to network issues connecting to cypress.
Documentation for the environment variable used:
https://docs.cypress.io/guides/references/advanced-installation#Skipping-installation
=> perf(npm): only install cypress when needed

workflow-templates/lint-eslint.yml, workflow-templates/node.yml, workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml
* Before Talk merges failed to execute the jobs: https://github.com/nextcloud/spreed/actions/runs/6530409072
* Fixed Talk: https://github.com/nextcloud/spreed/actions/runs/6531152220
=> Fix logic to run tests on pushes

workflow-templates/command-compile.yml
https://buildjet.com/for-github-actions/blog/launch-buildjet-cache
Caching with `action/cache` is insanely slow with self hosted. Like over 10 min for server...
https://github.com/nextcloud/server/actions/runs/6570701070/job/17848594960
=> perf: use `buildjet/cache` instead of `action/cache`

workflow-templates/node-test.yml
Similar to `node` and `phpunit`: Only run node tests if required.
=> feat(node-tests): Only run if required

workflow-templates/command-compile.yml, workflow-templates/cypress.yml, workflow-templates/lint-eslint.yml, workflow-templates/node.yml
Upstreaming https://github.com/nextcloud/server/pull/40733
I'm uncertain if skip puppeteer download is a reasonable default for everyone. 
Beside server only text has puppeteer as dependency.
=> ci: skip puppeteer chrome download

workflow-templates/phpunit-mariadb.properties.json, workflow-templates/phpunit-mariadb.yml
The workflow name and description says MySQL but MariaDB was used.
Instead use MySQL but provide an optional MariaDB template.
=> fix: Correctly use MySQL for phpunit-mysql and add phpunit-mariadb for  MariaDB

SECURITY.md
Offshoot of nextcloud/server#40966.
One caveat: I think the line added in https://github.com/nextcloud/.github/commit/6c456914c9914c6a352717e2f58bb71cd026aa93 in the existing Security Policy was probably trying to accommodate maybe either some of the "hosted" but still fairly independent sub-projects and/or maybe a way to accommodate reports about third-party maintained apps.
a) Is my guess accurate?
b) Should we try to accommodate that still?
c) If so, maybe we can find a clearer way to state that?
If a/b/c === true then we can add it to this PR before it gets merged if deemed appropriate.
=> Update SECURITY.md - Bring it up to par with the one in `server`

workflow-templates/psalm-matrix.yml, workflow-templates/psalm.yml
The name of the psalm multi-branch action to add to the branch protection was `static-psalm-analysis-summary` which is good and logical to find.
The name of the stable branched psalm action was `Nextcloud` which is very little straight forward.
=> fix(psalm): Improve name of psalm action

workflow-templates/renovate-approve-merge.yml
Similar to `dependabot-approve-merge`
but using the mechanisms of `update-nextcloud-ocp-approve-merge`.
Currently used in `text`, PR pending in `collectives`.
=> enh(workflow-templates): approve and automerge renovate PRs

workflow-templates/phpunit-mariadb.yml, workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml
Automatically run sqlite tests against all server versions listed as supported in `info.xml` and the minimum supported php version for the server version.
Example run: https://github.com/nextcloud/files_antivirus/actions/runs/6736095943
(also set `nextcloud/ocp` to not be installed as it is specific to server/php versions and only needed for psalm anyway)
=> automatically determine php/server versions for phpunit

workflow-templates/command-compile.yml
Already in place on server https://github.com/nextcloud/server/blob/master/.github/workflows/command-compile.yml
The workspace path changes and if the init step ran on a different host than the process step, it would fail.
No [failure since a few days](https://github.com/nextcloud/server/actions/workflows/command-compile.yml?query=is%3Afailure) on server because of this
=> fix(command-compile): fix workspace path and compatibility with self-hosted runners

workflow-templates/command-compile.properties.json, workflow-templates/command-compile.yml
```sh
/compile
/compile amend /
/compile fixup /
/compile rebase-amend /
/compile rebase-fixup /
```
PS: it will NOT resolve conflicts for you (could be amazing to drop any conflicts on `/js` or `/dist`)
1. https://github.com/nextcloud/privacy/pull/1022#issuecomment-1921072459
2. https://github.com/nextcloud/privacy/actions/runs/7740264658?pr=1022
=> fix(command-compile): rebase before compiling and fetch origin

workflow-templates/phpunit-mariadb.yml, workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml
instead of using the max supported php version for the phpunit jobs where we only test a single php version, pick a version that is available in the repos of the runner. This should speedup php installation.
In the case where there is no supported php version in the repos, it will fallback to the max php version.
See https://github.com/icewind1991/files_inotify/actions/runs/7789300829 for a test run.
=> select a php version available on the runner for phpunit

workflow-templates/phpunit-mariadb.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml
To match Mariadb and Mysql formats
https://github.com/nextcloud/.github/blob/7e27df30425f31d25bba08fc71d81874b75d3826/workflow-templates/phpunit-mariadb.yml#L67
https://github.com/nextcloud/.github/blob/7e27df30425f31d25bba08fc71d81874b75d3826/workflow-templates/phpunit-mysql.yml#L65
=> fix(phpunit): unify job names

workflow-templates/cypress.yml
On small apps there's no need for parallelization.
This allows the workflow to run without using the cypress cloud and removes the requirement to configure the secret.
=> Allow running cypress without a record key

workflow-templates/npm-audit-fix.yml
Fixing npm audit potentially means the change has effect for the product and requires a fix. Repos that use release automation would skip releases if there are only "chore" commits since the last tag. A security fix should definitely cause a release. The change should also go onto the changelog (again "chore" being typically ignored for this).
=> fix(npmauditfix): Make commit semantic

workflow-templates/npm-publish.yml
This does not work anymore since we have a second organization. Because our packahes are scope to `@nextcloud` but developed in `@nextcloud-libraries`.
=> fix(node-publish): Do not try to publish on Github Registry

workflow-templates/block-merge-eol.yml
Regression introduced by nextcloud-releases/updater_server#1014
=> fix: check EOL on stable only if beta not available

workflow-templates/openapi.yml
If you try using this workflow it will fail because the `versions` step is defined twice.
=> fix(workflow-templates): Adjust duplicate versions steps in OpenAPI workflow

workflow-templates/appstore-build-publish.yml
* Do not install any dev dependencies during the build.
* Pass if there is no `build` script. Some apps (*cough*`data_request`*cough*) have a `package.json` just for cypress tests.
=> enh(appstore-build-publish): without dev dependencies

workflow-templates/reuse.yml
=> fix(reuse): Rename the job so it can be easily required on PRs

workflow-templates/lint-eslint.yml, workflow-templates/node-test.yml, workflow-templates/node.yml, workflow-templates/phpunit-mariadb.yml, workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml
For Nextcloud GmbH repositories this is required to allow the `dorny/paths-filter` action to access GitHub API for fetching changed files.
=> fix: Add `pull-requests: read` permission to changes step

workflow-templates/appstore-build-publish.yml
- Revert of https://github.com/nextcloud/.github/pull/347
- but keep `--if-present`
Unlink true Node.js apps, in frontend apps separation between `dependencies` and `devDependencies` is often used to separate:
- `dependencies` = runtime libraries used in the frontend app 
- `devDependencies` = development tools including 
- bundling/compiling
- testing
- linting/formatting
Getting rid of dev deps removes not only testing, but also building tools.
Using `NODE_ENV=production` makes sense for Node.js apps, but for Nextcloud frontend apps it breaks building.
Found by @Antreesy 
https://github.com/nextcloud-releases/spreed/actions/runs/9945797953/job/27474981578
In all the apps use `devDependencies` only for testing/development packages and `dependencies` for both production build/compile and …
=> fix(appstore-build-publish): keep dev dependencies to build frontend 

workflow-templates/command-compile.yml, workflow-templates/cypress.yml
=> chore: update buildjet/cache

workflow-templates/appstore-build-publish.yml
Checks that the tag name matching the version defined in the info.xml.
Mainly intended to prevent accidentally creating a release against the wrong branch.
Fixes #305
=> validate app version from info.xml against the tag name in public action

.github/ISSUE_TEMPLATE/1_bug_report.md, .github/ISSUE_TEMPLATE/2_feature_request.md
Seems that when adding the config with links only, there is no default option for bug reporting anymore (only the "without template" at the end):
> ![grafik](https://github.com/user-attachments/assets/67681daf-98b1-46e9-9435-0f99efadc283)
So adding a very basic simple template now.
In agreement with @AndyScherzinger the default template must be kept very simple and empty-reporting should be enabled
=> feat(issue-template): Add default templates

.github/ISSUE_TEMPLATE/1_bug_report.md.license, .github/ISSUE_TEMPLATE/2_feature_request.md.license, LICENSES/AGPL-3.0-or-later.txt
Adds the missing license file (already used in https://github.com/nextcloud/.github/blob/master/.github/ISSUE_TEMPLATE/config.yml) and adds the license to the new files. I assume those were copied from server so they must also be AGPL-3.0-or-later?
After this is merged please set reuse compliance to be required for merging PRs to avoid this in the future.
=> fix: REUSE compliance

workflow-templates/pr-feedback.yml
Avoid running it on the gmbh org or any other place where we don't want to post the feedback comments.
=> fix(workflow-templates): Only run pr-feedback on the nextcloud org

workflow-templates/lint-php-cs.yml, workflow-templates/psalm.yml
Follow-up to https://github.com/nextcloud/.github/pull/458
They are currently installing PHP 8.4 but [PHP-CS-Fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer?tab=readme-ov-file#supported-php-versions) and [Psalm](https://github.com/vimeo/psalm/issues/11107) are not yet compatible.
AFAIK, `php-available` is kind of a performance optimization. On the other hand, this blocks CI on apps until PHP 8.4 is ready for production.
Failing workflow: https://github.com/nextcloud/twofactor_totp/actions/runs/11918557008/job/33216257705?pr=1580
Fixed workflow: https://github.com/nextcloud/twofactor_totp/actions/runs/11919662884/job/33219864123?pr=1580
Failing workflow: https://github.com/nextcloud/twofactor_totp/actions/runs/11919662892/job/33219863665?pr=1580
Fixed workflow: …
=> fix: set up minimum supported instead of available php version

workflow-templates/psalm-matrix.yml, workflow-templates/psalm.yml
As discussed the other day with @st3iny 
@st3iny 
> Sounds good, but psalm will probably take some more time: https://github.com/vimeo/psalm/issues/11107
@nickvergessen 
> https://github.com/nextcloud/spreed/actions/runs/11930485130/job/33251359582 talk psalm works on 8.4
it doesnt have a hardcoded version check breaking it
might of course depend on edge cases your code triggers
but I would think Talk is pretty edgy
@st3iny 
> There are some deprecation warnings and it broke in one of my maintained apps though
Can't remember which one
@nickvergessen 
> the other fix for psalm is making sure you have the correct base version
https://github.com/nextcloud/spreed/blob/main/psalm.xml#L8
otherwise it checks your code to only be compatible with the actually used php version
instead of the …
=> fix(psalm): Enforce that psalm is executed against the minimum PHP version

workflow-templates/command-openapi.properties.json, workflow-templates/command-openapi.yml, workflow-templates/openapi.yml
- Successfully tested in https://github.com/nextcloud/spreed/pull/13886 + https://github.com/nextcloud/spreed/actions/runs/12057578195/job/33622526539
=> feat(openapi): Add command to regenerate OpenAPI

workflow-templates/npm-audit-fix.yml
main or master branch is always missing, so ignore missing branch and simply continue and do nothing.
Inspired by update-nextcloud-ocp workflow.
=> feat(npm-audit-fix): ignore missing branch, to avoid failure on main/master

workflow-templates/reuse.yml
Changes to js dependencies may break compliance.
This only becomes apparent after compiling the js.
Make sure the check runs on the actual js after the compilation so errors are shown for commits that do not include artifacts.
=> fix(reuse): compile before checking compliance

workflow-templates/reuse.yml
Reverts nextcloud/.github#478
As brought up by https://github.com/nextcloud/.github/pull/478#issuecomment-2556555950 this breaks repos without compiled js
=> Revert "fix(reuse): compile before checking compliance"

workflow-templates/command-compile.yml
https://github.com/nextcloud/server/commit/69b4a6cc19683769a92ebbdb0a687cde48ad0ffb
https://github.com/nextcloud/server/actions/runs/12784402160/job/35637333846?pr=50172
=> fix(command-compile): persist-credentials for compile bot to allow rebae and force push

workflow-templates/phpunit-mariadb.yml
For the upcoming release we should make sure to test the supported versions.
Lower bound is 10.6 and upper bound is 11.4
=> fix: Update MariaDB versions to supported versions of Nextcloud 31

.github/workflows/dispatch-workflow.yml, .github/workflows/lint-yaml.yml, .github/workflows/reuse.yml, workflow-templates/appstore-build-publish.yml, workflow-templates/command-compile.yml, workflow-templates/command-openapi.yml, workflow-templates/cypress.yml, workflow-templates/dependabot-approve-merge.yml, workflow-templates/documentation.yml, workflow-templates/npm-audit-fix.yml, workflow-templates/pr-feedback.yml, workflow-templates/psalm-matrix.yml, workflow-templates/psalm.yml, workflow-templates/renovate-approve-merge.yml, workflow-templates/reuse.yml, workflow-templates/update-nextcloud-ocp-matrix.yml, workflow-templates/update-nextcloud-ocp.yml
- Based on #495 to allow to see green CI
- Ref https://woodruffw.github.io/zizmor/audits/#remediation_15
=> fix: Harden approve-merge checks

workflow-templates/phpunit-mariadb.yml
In MariaDB 11 there was a "breaking" change in the docker files that removed the legacy `mysqladm` and replaced it with `mariadb-admin`. The symlink is not provided in the docker image so we need to use the correct name here to make 10.6 AND 11.4 work.
Also the `MYSQL_` env variables are deprecated and will be removed.
---
Alternative for the first change would be to use the `healthcheck.sh` provided by the image, but that requires us to rebuild all mariadb images as it was added in later version for 10.2 / 10.3 / 10.4 / 10.5 and 10.6. It is already included in our 11.4 image though.
=> fix(phpunit-mariadb): Use correct script name and env variable

workflow-templates/cypress.yml
Needed as we are compiling the front end during that step.
This is a limitation for photos where I need to fix that when I update the workflows.
=> fix: Use normal container for cypress init

workflow-templates/psalm-matrix.yml
As we might not be able to upgrade psalm 6 and 8.4 e.g. complains when using Psalm 5.26 about missing nullable typehints
=> fix(psalm): Run matrix psalm on the lowest applicable PHP version

.github/workflows/dispatch-workflow.yml
1. There is a common type `ci` for changes to CI
2. Simplify verb
3. Lower case description
Ref https://www.conventionalcommits.org/en/v1.0.0/#summary
=> fix: use more conventional commit message for workflow updates

workflow-templates/lint-php-cs.yml, workflow-templates/phpunit-mariadb.yml, workflow-templates/phpunit-mysql.yml, workflow-templates/phpunit-oci.yml, workflow-templates/phpunit-pgsql.yml, workflow-templates/phpunit-sqlite.yml, workflow-templates/psalm-matrix.yml, workflow-templates/psalm.yml
Fixes https://github.com/nextcloud/.github/issues/537
The `--no-scripts` option ensures the `post-update-cmd` from the composer-bin plugin is not executed, so only the main composer.lock file will be updated. There doesn't seem to be a proper way to disable command forwarding for single commands with the composer-bin plugin.
=> fix: Do not update dependencies in vendor-bin when removing nextcloud/ocp

workflow-templates/pr-feedback.yml
- `nextcloud/pr-feedback-action` version bump includes https://github.com/nextcloud/pr-feedback-action/pull/2.
- Start date is bumped for a same reason as in https://github.com/nextcloud/.github/commit/d7257d0e6298aace6a627c796390c5490f6be33b.
=> chore(deps): bump pr-feedback-action, bump start-date value to prevent spam

workflow-templates/update-nextcloud-ocp-matrix.yml
- Default instead of hardcoded master/main (idea stolen from #561 )
- Use version matrix to calculate the target branch
- …
- Profit: No more diff when updating this action in apps that support a different oldest branch and use main
=> ci(ocp): Remove hardcoded names from matrix OCP branch updates

workflow-templates/command-compile.yml
Sometimes it fails because it asks for the editor.
This disables it and make it non interactive
=> fix(command-compile): disable editing commit when rebasing

workflow-templates/block-merge-eol.yml
Since https://github.com/nextcloud-releases/updater_server/pull/1082 day is included in `major_versions.json`.
This fix account for it
=> fix(eol): EOL now include day in major versions desc
